version: '3.4'

services:
  rabbitmq:
    image: masstransit/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  eventstoredb:
    image: eventstore/eventstore:21.10.0-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - '1113:1113'
      - '2113:2113'
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16688:16686"
  mongo:
    image: mongo
    ports:
      - 27019:27017
  eventsourcing.webapi:
    image: ${DOCKER_REGISTRY-}eventsourcingwebapi
    build:
      context: .
      dockerfile: src/EventSourcing.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"
  eventsourcing.service:
    image: ${DOCKER_REGISTRY-}eventsourcingservice
    build:
      context: .
      dockerfile: src/EventSourcing.Service/Dockerfile